/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.view;

import com.senac.util.ReportXLS;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * 
 */
public class FrontEnd extends javax.swing.JFrame {

    public FrontEnd(String usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuVenda = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        menuVDFuncionario = new javax.swing.JMenuItem();
        menuVDCliente = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuCadProduto = new javax.swing.JMenuItem();
        menuFerramentas = new javax.swing.JMenu();
        menuCalc = new javax.swing.JMenuItem();
        menuNotepad = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cantina - 1.0.0.1");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuVenda.setText("Efetuar Venda");
        menuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendaActionPerformed(evt);
            }
        });
        menuArquivo.add(menuVenda);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menuBar.add(menuArquivo);

        menuReport.setText("Report");

        menuVDFuncionario.setText("Vendas por Funcionário");
        menuVDFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVDFuncionarioActionPerformed(evt);
            }
        });
        menuReport.add(menuVDFuncionario);

        menuVDCliente.setText("Vendas por Cliente");
        menuVDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVDClienteActionPerformed(evt);
            }
        });
        menuReport.add(menuVDCliente);

        menuBar.add(menuReport);

        menuCadastrar.setText("Gerenciar");

        menuCadCliente.setText("Cliente");
        menuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadCliente);

        menuCadFuncionario.setText("Funcionário");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadFuncionario);

        menuCadProduto.setText("Produto");
        menuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadProduto);

        menuBar.add(menuCadastrar);

        menuFerramentas.setText("Ferramentas");

        menuCalc.setText("Calculadora");
        menuCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalcActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuCalc);

        menuNotepad.setText("Bloco de Notas");
        menuNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotepadActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuNotepad);

        menuBar.add(menuFerramentas);

        menuAjuda.setText("Ajuda");

        menuSobre.setText("Sobre...");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        menuHelp.setText("Ajuda");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        menuAjuda.add(menuHelp);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClienteActionPerformed
        cadastrarCliente();
    }//GEN-LAST:event_menuCadClienteActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutoActionPerformed
        cadastrarProduto();
    }//GEN-LAST:event_menuCadProdutoActionPerformed

    private void menuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendaActionPerformed
        new FrontEndVendas(usuario).setVisible(true);
    }//GEN-LAST:event_menuVendaActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalcActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Calculadora indispoível", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuCalcActionPerformed

    private void menuNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotepadActionPerformed
        try {
            Runtime.getRuntime().exec("notepad");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Bloco de notas indisponivel", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuNotepadActionPerformed

    private void menuVDFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVDFuncionarioActionPerformed
        ReportXLS rp = new ReportXLS();
        try {
            rp.reportPorFuncionario();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuVDFuncionarioActionPerformed

    private void menuVDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVDClienteActionPerformed
        ReportXLS rp = new ReportXLS();
        int matricula = Integer.parseInt(JOptionPane.showInputDialog("Matricula do cliente:"));
        try {
            rp.reportUsuario(matricula);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuVDClienteActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Nossa cantina.\nDeveloped by: Fabiano Demetrio e Priscila Duarte");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        new Ajuda().setVisible(true);
    }//GEN-LAST:event_menuHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuCadProduto;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCalc;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuNotepad;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem menuVDCliente;
    private javax.swing.JMenuItem menuVDFuncionario;
    private javax.swing.JMenuItem menuVenda;
    // End of variables declaration//GEN-END:variables
    private String usuario;

    // => quando for inserir cliente
    public void cadastrarCliente() {
        ClientesGerenciar cc = new ClientesGerenciar();
        desktop.removeAll();
        cc.setVisible(true);
        desktop.add(cc);
        SwingUtilities.updateComponentTreeUI(desktop);
    }

    // => quando for inserir funcionario
    public void cadastrarFuncionario() {
        FuncionariosGerenciar fc = new FuncionariosGerenciar();
        desktop.removeAll();
        fc.setVisible(true);
        desktop.add(fc);
        SwingUtilities.updateComponentTreeUI(desktop);
    }

    // => quando for inserir produto
    public void cadastrarProduto() {
        ProdutosGerenciar pc = new ProdutosGerenciar();
        desktop.removeAll();
        pc.setVisible(true);
        desktop.add(pc);
        SwingUtilities.updateComponentTreeUI(desktop);
    }
}
